### ISSUE TITLE
Front end scripts issue with caching plugins.

### ISSUE THREAD

**Issue by mdorchain** [FacetWP/facetwp-color#6]
Hi,

With the recent version of facetwp, I started to see issues due to the inlining of the front end javascript in the front_scripts(). The inline script can be loaded to early, before wp.hooks are loaded.
This seems to happen with caching plugins using js concatenation.

Instead of inlining, I think it should be better to use FWP()->display->assets to prevent loading order issues. This is already handle this way in the core facets.

Example:
FWP()->display->assets[ 'facetwp-color' ] = plugin_dir_url( __FILE__ ) . '/facetwp-color.js';

facetwp-color.js will just contained the existing js previously inlined.

Thanks

Michael

**Comment by mgibbs189** [comment]
Hey @mdorchain you're right, we should definitely be using `FWP()->display->assets` instead. It looks like a bunch of add-ons need to be adjusted accordingly. I'll try to get the add-ons patched up early next week-ish.

**Comment by mgibbs189** [comment]
We've _finally_ addressed this issue. Thanks for your patience @mdorchain 👍
